baseURL: https://averyan.ru
languageCode: ru-ru
paginate: 5
title: AveryanAlex
enableEmoji: true

languages:
  ru:
    languageName: Русский
    title: AveryanAlex
    weight: 1

DefaultContentLanguage: ru
hasCJKLanguage: false

permalinks:
  post: /p/:slug/
  page: /:slug/

params:
  mainSections:
    - post
  featuredImageField: image
  rssFullContent: true
  favicon:

  footer:
    since: 2022
    customText:

  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST

  sidebar:
    subtitle: Alexander Averyanov
    avatar:
      enabled: true
      local: false
      src: /img/avatar.png

  article:
    math: false
    toc: true
    readingTime: true
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0

  comments:
    enabled: false

  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

  opengraph:
    twitter:
      site:
      card: summary_large_image

  defaultImage:
    opengraph:
      enabled: false
      local: false
      src:

  colorScheme:
    toggle: true
    default: auto

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

menu:
  main: []

  social:
    - identifier: github
      name: GitHub
      url: https://github.com/averyanalex/
      params:
        icon: brand-github

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200

markup:
  goldmark:
    renderer:
      unsafe: false
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4

module:
  imports:
    - path: github.com/CaiJimmy/hugo-theme-stack/v3
